### ISSUE TITLE
搭建环境运行出现Access to XMLHttpRequest at 'http://localhost/vue-admin-php/public/index.php/admin/login/out'

### ISSUE THREAD

**Issue by lilei132** [lmxdawn/vue-admin-php#8]
进入http://localhost:8080/vue-admin-html/dist/index.html#/后，出现请求问题，localhost：8080可以访问到，请问如何修改，解决。
Access to XMLHttpRequest at 'http://localhost/vue-admin-php/public/index.php/admin/login/out' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by lmxdawn** [comment]
跨域问题, 请在 Nginx 或者 Apache 里面配置跨域

**Comment by lilei132** [comment]
打扰了，请问有没有具体一点的解决办法，我尝试了很多但是都不可以，其次是请求的localhost地址，我想改为localhost:8000，在env设置后，并未生效，请问有什么解决办法。多谢您
